<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>My Application</title>

        <!-- Bootstrap core CSS -->

        <link href="/node_modules/bootstrap-4/dist/css/bootstrap.min.css" rel="stylesheet">
        <link href="/css/app.css" rel="stylesheet">
    </head>
    <body>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
            <a class="navbar-brand" href="#">My Application</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <?php if (Helper::isLogged()) { ?>
                <div class="collapse navbar-collapse" id="navbarsExampleDefault">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="/home">Home <span class="sr-only">(current)</span></a>
                        </li>
                        <!-- <li class="nav-item">
                            <a class="nav-link" href="#">Link</a>
                        </li>-->
                        <?php if (Helper::isLogged()) { ?>
                            <li class="nav-item">
                                <a class="nav-link" href="/product">Products</a>
                            </li>
                            
                            <li class="nav-item">
                                <a class="nav-link" href="/login/end">Logout</a>
                            </li>
                        <?php } ?>
                    </ul>
                </div>
            <?php } ?>
        </nav>
        <main role="main" class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <?php echo $data['content']; ?>
                </div>
            </div>
        </main>
    </div>
</body>
</html>

