<?php
$product = [];
$product['code'] = !empty($data['product']->code) ? $data['product']->code : '';
$product['name'] = !empty($data['product']->name) ? $data['product']->name : '';
$product['price'] = !empty($data['product']->price) ? $data['product']->price : '';
?>
<nav aria-label="breadcrumb" role="navigation">
    <ol class="breadcrumb">
        <li class="breadcrumb-item" aria-current="page">Products</li>
        <li class="breadcrumb-item active" aria-current="page">Edit</li>
    </ol>
</nav>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-4">
            <form>
                <div class="form-group">
                    <label class="col-form-label" for="code">Product Code</label>
                    <input type="text" class="form-control" id="code" name="code" placeholder="Product Code" value="<?=$product['code']?>">
                </div>
                <div class="form-group">
                    <label class="col-form-label" for="name">Product Name</label>
                    <input type="text" class="form-control" id="name" name="name" placeholder="Product Name" value="<?=$product['name']?>">
                </div>
                <div class="form-group">
                    <label class="col-form-label" for="name">Product Price</label>
                    <input type="text" class="form-control" id="price" name="price" placeholder="Product Price" value="<?=$product['price']?>">
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Update</button>
                </div>
            </form>
        </div>
    </div>
</div>
