<div class="row">
    <?php
    if(isset($data['messages'])){
        echo $data['messages']['error'];
    }
    ?>
    <div class="col-md-4 offset-md-4">
        <h2>Login</h2>
        <hr/>
    </div>
    
    <div class="col-md-4 offset-md-4">
        <form method="post" action="/login/auth">
            <div class="form-group">
                <label for="exampleInputEmail1">Email address</label>
                <input type="text" class="form-control" id="username" name="username" aria-describedby="emailHelp" placeholder="Enter Username">
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Password</label>
                <input type="password" name="password" class="form-control" id="password" placeholder="Password">
            </div>
            <button type="submit" class="btn btn-primary">Login</button>
        </form>
    </div>
</div>
